"""empty message

Revision ID: 9de9d0d515df
Revises: 3c66fe41b69f
Create Date: 2023-02-15 13:30:53.032539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de9d0d515df'
down_revision = '3c66fe41b69f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'artist_id')
    )
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_constraint('Artist_venue_id_fkey', type_='foreignkey')
        batch_op.drop_column('venue_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('Artist_venue_id_fkey', 'Venue', ['venue_id'], ['id'])

    op.drop_table('shows')
    # ### end Alembic commands ###
